// Plate XLVII The Hyperbolic Plane, as a positive. The {p, q} tiling of
// the Poincare disk is generated by the three mirrors of its Schwarz
// triangle: reflection in the x axis, reflection in the line at pi/p,
// and inversion in the arc that carries the polygon's edge. Every point
// is born on that edge, at a place q.x picks between the two vertices,
// and is then pushed through a random word in the three mirrors, its
// own length drawn per point. The crowding at the rim is the metric,
// not the projection.
//
// Three of the shader's loops become three constructs. Raising q until
// (p-2)(q-2) > 4 is an orbit whose until() is the shader's own break.
// The word is an orbit too, and it carries two things one step ahead of
// their use, because an orbit field cannot both draw and be read by its
// siblings: m is the mirror in force this step, and uu is the uniform
// that will choose the next one. Two draws more than the plate in
// total; same law.
//
// The float-drift clamp fires at the end of a step, on the value that
// step just made, which simultaneous update cannot express. So the
// state carries the RAW reflected point and sc, the factor the clamp
// would have multiplied it by, and every read of z is zx * sc. The
// product is bit-identical to the shader's clamped z, and the reflected
// coordinates are written out at each site the way the Newton stanzas
// of the minimal-surface plate are.
import { positive, lever, pal, mix, clamp, cmul, cdiv, v2, TAU, PI } from "../core/measure.mjs";

export default positive("hyper_pos", {
  pgon:  lever("P",           3, 8,  1,    5),
  qval:  lever("Q",           3, 8,  1,    4),
  word:  lever("WORD LENGTH", 2, 24, 1,    12),
  model: lever("MODEL",       0, 1,  0.01, 0.0),
  color: lever("COLOR",       0, 1,  0.01, 0.55),
  glow:  lever("GLOW",        0, 1,  0.01, 0.6),
  cam: { dist: 2.9, pitch: 0.55, tgtY: 0.0, rot: 0.03 },
  gain: 0.85, accent: "#90b8f0",
},
(P, s, q, t) => {
  // the Schwarz triangle {p, q}: regular p-gons meeting q to a vertex.
  // The tiling is hyperbolic exactly when cos^2(pi/q) exceeds
  // sin^2(pi/p), so a spherical or Euclidean pair is pushed into the
  // hyperbolic range by raising q until it is.
  const np = Math.max(3.0, Math.min(8.0, Math.floor(P.pgon + 0.5)));
  const nq0 = Math.max(3.0, Math.min(8.0, Math.floor(P.qval + 0.5)));
  const sp = Math.sin(PI / np);
  const raise = s.orbit(8, { nq: nq0, cq: Math.cos(PI / nq0) }, (v) => ({
    nq: v.nq + 1.0,
    cq: Math.cos(PI / (v.nq + 1.0)),
  }), { until: (v) => v.cq * v.cq - sp * sp > 1.0e-4 });
  const cq = raise.cq;

  // the polygon's edge is an arc of the circle centred at (d, 0) with
  // radius r, and d*d - r*r = 1 makes it meet the unit circle at right
  // angles, which is what a hyperbolic line is
  const root = Math.sqrt(Math.max(cq * cq - sp * sp, 1.0e-6));
  const d = cq / root;
  const r = sp / root;
  const wedge = PI / np;

  // the birth place: the sub-arc between the two vertices, found where
  // the wedge boundary at angle pi/p cuts the circle
  const cw = Math.cos(wedge);
  const tv = d * cw - Math.sqrt(Math.max(d * d * cw * cw - 1.0, 0.0));
  const cpsiv = clamp((d - tv * cw) / Math.max(r, 1.0e-9), -1.0, 1.0);
  const psiv = Math.acos(cpsiv);
  const psi = (q.x - 0.5) * 2.0 * psiv;
  const zx0 = d - r * Math.cos(psi);
  const zy0 = 0.0 - r * Math.sin(psi);
  if (Math.abs(Math.atan2(zy0, zx0)) > wedge || zx0 * zx0 + zy0 * zy0 >= 1.0) {
    return s.decline();
  }

  // how many generations this point walks, and the first letter of its
  // word: with no last mirror to avoid, the first is any of the three
  const wlen = Math.max(2.0, Math.min(24.0, Math.floor(P.word + 0.5)));
  const klen = Math.floor(s.u() * wlen);
  const first = s.u();
  const Rv = v2(Math.cos(TAU / np), Math.sin(TAU / np));

  // the word itself. m is the mirror this step applies, uu the uniform
  // that picks the next one, and a letter never repeats its
  // predecessor, so each uniform chooses between the other two.
  const w = s.orbit(24, {
    zx: zx0, zy: zy0, sc: 1.0,
    m: 1.0 + Math.floor(first * 2.99999),
    uu: s.u(),
    left: klen,
  }, (v) => ({
    zx: ((v.m == 1.0) ? v.zx * v.sc
          : (v.m == 2.0) ? cmul(Rv, v2(v.zx * v.sc, -(v.zy * v.sc))).x
          : d + r * r * (v.zx * v.sc - d) / ((v.zx * v.sc - d) * (v.zx * v.sc - d) + (v.zy * v.sc) * (v.zy * v.sc) + 1.0e-9)),
    zy: ((v.m == 1.0) ? -(v.zy * v.sc)
          : (v.m == 2.0) ? cmul(Rv, v2(v.zx * v.sc, -(v.zy * v.sc))).y
          : r * r * (v.zy * v.sc) / ((v.zx * v.sc - d) * (v.zx * v.sc - d) + (v.zy * v.sc) * (v.zy * v.sc) + 1.0e-9)),
    sc: (((v.m == 1.0) ? v.zx * v.sc
            : (v.m == 2.0) ? cmul(Rv, v2(v.zx * v.sc, -(v.zy * v.sc))).x
            : d + r * r * (v.zx * v.sc - d) / ((v.zx * v.sc - d) * (v.zx * v.sc - d) + (v.zy * v.sc) * (v.zy * v.sc) + 1.0e-9)) * ((v.m == 1.0) ? v.zx * v.sc
            : (v.m == 2.0) ? cmul(Rv, v2(v.zx * v.sc, -(v.zy * v.sc))).x
            : d + r * r * (v.zx * v.sc - d) / ((v.zx * v.sc - d) * (v.zx * v.sc - d) + (v.zy * v.sc) * (v.zy * v.sc) + 1.0e-9))
      + ((v.m == 1.0) ? -(v.zy * v.sc)
            : (v.m == 2.0) ? cmul(Rv, v2(v.zx * v.sc, -(v.zy * v.sc))).y
            : r * r * (v.zy * v.sc) / ((v.zx * v.sc - d) * (v.zx * v.sc - d) + (v.zy * v.sc) * (v.zy * v.sc) + 1.0e-9)) * ((v.m == 1.0) ? -(v.zy * v.sc)
            : (v.m == 2.0) ? cmul(Rv, v2(v.zx * v.sc, -(v.zy * v.sc))).y
            : r * r * (v.zy * v.sc) / ((v.zx * v.sc - d) * (v.zx * v.sc - d) + (v.zy * v.sc) * (v.zy * v.sc) + 1.0e-9)) > 0.998001)
      ? 0.999 * (1.0 / Math.sqrt(((v.m == 1.0) ? v.zx * v.sc
                : (v.m == 2.0) ? cmul(Rv, v2(v.zx * v.sc, -(v.zy * v.sc))).x
                : d + r * r * (v.zx * v.sc - d) / ((v.zx * v.sc - d) * (v.zx * v.sc - d) + (v.zy * v.sc) * (v.zy * v.sc) + 1.0e-9)) * ((v.m == 1.0) ? v.zx * v.sc
                : (v.m == 2.0) ? cmul(Rv, v2(v.zx * v.sc, -(v.zy * v.sc))).x
                : d + r * r * (v.zx * v.sc - d) / ((v.zx * v.sc - d) * (v.zx * v.sc - d) + (v.zy * v.sc) * (v.zy * v.sc) + 1.0e-9))
          + ((v.m == 1.0) ? -(v.zy * v.sc)
                : (v.m == 2.0) ? cmul(Rv, v2(v.zx * v.sc, -(v.zy * v.sc))).y
                : r * r * (v.zy * v.sc) / ((v.zx * v.sc - d) * (v.zx * v.sc - d) + (v.zy * v.sc) * (v.zy * v.sc) + 1.0e-9)) * ((v.m == 1.0) ? -(v.zy * v.sc)
                : (v.m == 2.0) ? cmul(Rv, v2(v.zx * v.sc, -(v.zy * v.sc))).y
                : r * r * (v.zy * v.sc) / ((v.zx * v.sc - d) * (v.zx * v.sc - d) + (v.zy * v.sc) * (v.zy * v.sc) + 1.0e-9))))
      : 1.0,
    m: (v.m == 1.0) ? ((v.uu < 0.5) ? 2.0 : 3.0)
     : (v.m == 2.0) ? ((v.uu < 0.5) ? 1.0 : 3.0)
     : ((v.uu < 0.5) ? 1.0 : 2.0),
    uu: s.u(),
    left: v.left - 1.0,
  }), { until: (v) => v.left <= 0.0 });

  // the word's end, the clamp factor spent
  const zx1 = w.zx * w.sc;
  const zy1 = w.zy * w.sc;

  // gentle intrinsic motion: a small Mobius automorphism of the disk is
  // an isometry, so the whole tiling slides rigidly under it
  const aax = 0.05 * Math.cos(t * 0.10);
  const aay = 0.05 * Math.sin(t * 0.073);
  const cm = cmul(v2(aax, -aay), v2(zx1, zy1));
  const zw = cdiv(v2(zx1 + aax, zy1 + aay), v2(1.0 + cm.x, cm.y));
  let zx2 = zw.x, zy2 = zw.y;
  const zz2 = zx2 * zx2 + zy2 * zy2;
  if (zz2 > 0.998001) {
    const drift = 0.999 * (1.0 / Math.sqrt(zz2));
    zx2 *= drift;
    zy2 *= drift;
  }

  // the disk model lies flat in xz; MODEL lifts it onto the
  // hyperboloid, where anything past |z| = 0.985 leaves the frame
  const mdl = clamp(P.model, 0.0, 1.0);
  const s2 = zx2 * zx2 + zy2 * zy2;
  if (mdl > 0.001 && s2 > 0.970225) { return s.decline(); }
  const den = Math.max(1.0 - s2, 1.0e-4);

  // colour tints the generations into rings
  return s.deposit({
    xyz: [mix(zx2 * 1.2, 0.6 * zx2 / den, mdl),
          mix(0.0, 0.3 * (1.0 + s2) / den - 0.45, mdl),
          mix(zy2 * 1.2, 0.6 * zy2 / den, mdl)],
    col: pal(klen / wlen * 0.85 + P.color, [0.5, 0.5, 0.5], [0.5, 0.5, 0.5],
             [1.0, 1.0, 1.0], [0.0, 0.33, 0.67]),
    glow: 0.5 + 0.7 * P.glow,
  });
});
