// Generate harness/bench-all.html: the measurement bench with EVERY
// original plate and every built positive registered, plus
// build/bench-index.json mapping ids to registration indexes.
// Registration order is script order, so originals land at their true
// atlas indexes (0..67) and positives follow.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const platesDir = join(root, "..", "PrettyCloud", "atlas", "js", "plates");
const buildDir = join(root, "build");

const originals = readdirSync(platesDir).filter(f => /^\d+-.*\.js$/.test(f))
  .sort((a, b) => parseInt(a) - parseInt(b));
const positives = readdirSync(buildDir).filter(f => f.endsWith(".plate.js")).sort();

const tags = [];
const index = { originals: {}, positives: {} };
let idx = 0;
for (const f of originals) {
  tags.push(`<script src="../../PrettyCloud/atlas/js/plates/${f}"></script>`);
  const src = readFileSync(join(platesDir, f), "utf8");
  const m = /id:\s*"([^"]+)"/.exec(src);
  index.originals[m ? m[1] : f] = idx++;
}
for (const f of positives) {
  tags.push(`<script src="../build/${f}"></script>`);
  const src = readFileSync(join(buildDir, f), "utf8");
  const m = /id:\s*"([^"]+)"/.exec(src);
  index.positives[m ? m[1] : f] = idx++;
}

// bench.html is the source of truth for the harness body; swap the
// plate list between the core scripts and the renderer
const bench = readFileSync(join(root, "harness", "bench.html"), "utf8");
const anchorA = bench.indexOf("<!-- 0:");
const anchorB = bench.indexOf('<script src="../../PrettyCloud/atlas/js/core/renderer.js">');
if (anchorA < 0 || anchorB < 0) throw new Error("bench.html anchors moved");
const out = bench.slice(0, anchorA) +
  "<!-- generated by tools/gen-bench.mjs: all originals, then all positives -->\n" +
  tags.join("\n") + "\n" +
  bench.slice(anchorB);
writeFileSync(join(root, "harness", "bench-all.html"), out);
writeFileSync(join(buildDir, "bench-index.json"), JSON.stringify(index, null, 2));
console.log(`bench-all.html: ${originals.length} originals + ${positives.length} positives`);
