// Survey the plate corpus: which constructs recur, where, and how often.
// The language should be discovered from the plates, not legislated, so
// this tool measures the vocabulary the sixty-eight have already been
// speaking by convention. Output names the corpus it measured.
//
//   node tools/survey.mjs [path-to-plates.json]
//
// Detectors are regexes over each plate's GLSL plus its lever table.
// They are heuristics and say so; anything surprising in the tables
// should be checked against the plate source before it is believed.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = process.argv[2] || join(here, "..", "..", "atlas-darkroom", "plates.json");
const provPath = src.replace(/plates\.json$/, "plates.provenance.json");
if (!existsSync(src)) {
  console.error("no corpus at " + src + "; pass the path to plates.json");
  process.exit(1);
}
const plates = JSON.parse(readFileSync(src, "utf8"));
const prov = existsSync(provPath) ? JSON.parse(readFileSync(provPath, "utf8")) : null;

const count = (g, re) => (g.match(re) || []).length;

// ---- construct detectors -------------------------------------------
// keys become table columns; keep names short and honest
function signature(p) {
  const g = p.glsl || "";
  const labels = (p.params || []).map(x => x.label);
  return {
    // the semantic split: is the R2 point a coordinate in the object's
    // own parameter space, or hashed into a budget stream?
    qHashed: /floatBitsToUint\s*\(\s*q\.[xy]/.test(g),
    qUses: count(g, /\bq\.[xy]\b/g),
    // motion: does the object depend on simulation time at all
    timeRefs: count(g, /\buT\b/g),
    // addressing intensity
    hashu: count(g, /\bhashu\s*\(/g),
    streamHelper: /float\s+\w+_u\s*\(\s*inout\s+uint/.test(g),
    // the loupe and the lattice
    magnify: labels.includes("MAGNIFY"),
    windowInt: /ivec4\s+win\b/.test(g),
    intConsts: count(g, /\bconst\s+int\b/g),
    ivec2s: count(g, /\bivec2\b/g),
    // measure discipline
    culls: count(g, /-20000\.0/g),
    depthLever: labels.includes("DEPTH"),
    // iteration character: a loop whose bound starts lowercase is
    // (by house convention) data-dependent - a toll, not an unroll
    loops: count(g, /\bfor\s*\(/g),
    breaks: count(g, /\bbreak\s*;/g),
    tollLoop: /for\s*\(\s*int\s+\w+\s*=\s*\w+\s*;\s*\w+\s*<\s*[a-z]\w*\s*;/.test(g),
    wordRegister: /\buint\s+\w+\s*\[\s*\d+\s*\]/.test(g),
    // deposit & grade
    pal: count(g, /\bpal\s*\(/g),
    stainHelper: /\w+_stain\s*\(/.test(g),
    engines: /\bfmode\b/.test(g),
    complexLib: /\b(cmul|cdiv|cinv|csqrt)\s*\(/.test(g),
    // size
    lines: g.split("\n").length,
    chars: g.length,
    levers: labels,
  };
}

function family(s) {
  if (s.qHashed && s.windowInt) return "addressed+windowed";
  if (s.qHashed) return "addressed";
  if (s.complexLib) return "complex-map";
  return "coordinate-map";
}

const rows = plates.map(p => {
  const s = signature(p);
  return { index: p.index, roman: p.roman, id: p.id, name: p.name, s, fam: family(s) };
});

// ---- aggregates -----------------------------------------------------
const N = rows.length;
const prevalence = {};
for (const key of ["qHashed", "streamHelper", "magnify", "windowInt", "culls",
                   "depthLever", "tollLoop", "wordRegister", "stainHelper",
                   "engines", "complexLib", "timeRefs", "pal"]) {
  prevalence[key] = rows.filter(r => {
    const v = r.s[key];
    return typeof v === "boolean" ? v : v > 0;
  }).length;
}
const leverFreq = {};
for (const r of rows) for (const l of r.s.levers) leverFreq[l] = (leverFreq[l] || 0) + 1;
const famCount = {};
for (const r of rows) famCount[r.fam] = (famCount[r.fam] || 0) + 1;

// ---- emit -----------------------------------------------------------
const stamp = prov
  ? `corpus: ${prov.plates} plates from ${prov.source} @ ${String(prov.source_head).slice(0, 12)} (dumped ${prov.dumped_at})`
  : `corpus: ${N} plates from ${src} (no provenance file)`;

const flag = v => (v ? "x" : ".");
const lines = [];
lines.push("# The corpus, surveyed");
lines.push("");
lines.push("GENERATED by tools/survey.mjs - edit the tool, not this file.");
lines.push(stamp);
lines.push("");
lines.push("## Construct prevalence");
lines.push("");
lines.push("| construct | plates | of " + N + " |");
lines.push("|---|---|---|");
const NOTES = {
  qHashed: "the point is a budget draw, not a coordinate (hashes q into a stream)",
  streamHelper: "per-plate stream helper `float x_u(inout uint)`",
  magnify: "MAGNIFY lever (the site's loupe; editions expose at 0)",
  windowInt: "integer window `ivec4 win` with importance clipping",
  culls: "cull sentinel (returns the -20000 point): sampling can decline",
  depthLever: "DEPTH lever (a budget or a toll, plate by plate)",
  tollLoop: "data-dependent loop bound: rows earned, not unrolled",
  wordRegister: "word-array register (bit-parallel state)",
  stainHelper: "rotation-about-grey stain helper",
  engines: "furniture-request engines (`fmode` dispatch, one call site each)",
  complexLib: "shared complex arithmetic (cmul/cdiv/csqrt)",
  timeRefs: "references uT: the object moves",
  pal: "IQ palette deposits",
};
for (const [k, v] of Object.entries(prevalence)) {
  lines.push(`| ${k} | ${v} | ${(100 * v / N).toFixed(0)}% - ${NOTES[k]} |`);
}
lines.push("");
lines.push("## Families");
lines.push("");
for (const [f, c] of Object.entries(famCount).sort((a, b) => b[1] - a[1])) {
  lines.push(`- **${f}**: ${c} plates`);
}
lines.push("");
lines.push("## Lever vocabulary (label, plates carrying it)");
lines.push("");
const lf = Object.entries(leverFreq).sort((a, b) => b[1] - a[1]);
lines.push(lf.filter(([, c]) => c > 1).map(([l, c]) => `${l} ${c}`).join(" · "));
lines.push("");
lines.push(`plus ${lf.filter(([, c]) => c === 1).length} labels that appear exactly once (the subject-specific dials).`);
lines.push("");
lines.push("## Per-plate signatures");
lines.push("");
lines.push("| # | plate | id | family | lines | hashu | q→hash | window | cull | toll | register | engines | stain | moving |");
lines.push("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|");
for (const r of rows) {
  const s = r.s;
  lines.push(`| ${r.index + 1} | ${r.roman} | ${r.id} | ${r.fam} | ${s.lines} | ${s.hashu} | ${flag(s.qHashed)} | ${flag(s.windowInt)} | ${s.culls} | ${flag(s.tollLoop)} | ${flag(s.wordRegister)} | ${flag(s.engines)} | ${flag(s.stainHelper)} | ${flag(s.timeRefs > 0)} |`);
}
lines.push("");
writeFileSync(join(here, "..", "docs", "SURVEY.md"), lines.join("\n") + "\n");
writeFileSync(join(here, "..", "docs", "survey.json"),
  JSON.stringify({ stamp, prevalence, famCount, leverFreq, rows }, null, 1) + "\n");
console.log(stamp);
console.log(`wrote docs/SURVEY.md and docs/survey.json (${N} plates)`);
for (const [k, v] of Object.entries(prevalence)) console.log(`  ${k.padEnd(14)} ${String(v).padStart(3)} / ${N}`);
